### ISSUE TITLE
Upload files to s3

### ISSUE THREAD

**Issue by ctdk** [ctdk/goiardi#11]
Right now when cookbook files are uploaded they're stored locally. This is great and all, but it'd be nice to also allow uploading to a 3rd party storage service like s3.

**Comment by sampointer** [comment]
We did this way back in Chef 0.10.8 at EA to avoid brittle clustered filesystems, or worse NFS: https://vimeo.com/57861199

**Comment by ctdk** [comment]
By amazing coincidence I was already planning on getting this feature added. It's been on my mind for a while, obviously, but this would be a good thing to have (and is the last real blocker for HA goiardi, if you're using pg search).

**Comment by ctdk** [comment]
This is done, finally.
