### ISSUE TITLE
MYSQL Schema Errors on RDS

### ISSUE THREAD

**Issue by bramswenson** [ctdk/goiardi#37]
I had to remove the following two lines in order to get the schema to run in Amazon RDS MySQL (no SUPER):
https://github.com/ctdk/goiardi/blob/master/sql-files/goiardi-schema-mysql.sql#L649
https://github.com/ctdk/goiardi/blob/master/sql-files/goiardi-schema-mysql.sql#L668

Removing them allows an error free loading of the schema.

**Comment by ctdk** [comment]
Ah, of course. (I hadn't yet tried them on RDS yet.) I'm in the middle of a bunch of changes, but I'll try and get this turned around and tested quickly.

**Comment by ctdk** [comment]
Looked into it, seems to work fine without the DEFINER statements. I went ahead and put the change in. Thanks!
