### ISSUE TITLE
Client can't download from filestore after hostname change.

### ISSUE THREAD

**Issue by oker1** [ctdk/goiardi#40]
I've started goiardi without a hostname parameter, uploaded a cookbook. The client could download it. I've restarted the server with a hostname parameter, and the client tried the filestore urls with the old (default) hostname. After I've uploaded the cookbook again it worked.

**Comment by ctdk** [comment]
Strange. I remember this coming up at some point before, but I thought I fixed it. I'll take a look.

**Comment by ctdk** [comment]
Aha, I found it. (Been busy at work, I'm afraid.) Running tests on it now, but while the hostname for file URLs was being fixed almost everywhere, it was broken exactly one place. Unfortunately when I tested it before it managed to fetch it from the old place. A fix for this, assuming I didn't break something subtly with this, should be up in the morning.

**Comment by ctdk** [comment]
There's a fix in this for master. I'll be cutting a new release pretty soon too. Thanks for finding that this was still a problem.

**Comment by ctdk** [comment]
This has been released for about a month. Unless I hear otherwise I'm going to assume this fixed it.
