### ISSUE TITLE
Chef-Browser support?

### ISSUE THREAD

**Issue by joerg** [ctdk/goiardi#47]
I don't know if you are aware of the Chef-Browser Project [1] but this is a very nice and simple web frontend for the official chef-server and thus should also work with goiardi. Maybe someone could do a quick test of this with goiardi and if it works some small documentation (mainly that it exists and that it is an alternative to the old official frontend) would be nice.
They also provide a docker container [2] which for sure would be easiest way to get everything running.

[1] https://github.com/3ofcoins/chef-browser
[2] https://quay.io/repository/3ofcoins/chef-browser

**Comment by ctdk** [comment]
I was not aware, but I'll be taking a look at that this weekend. Thanks for the heads up; I imagine it would work fine with goiardi, certainly.

**Comment by ctdk** [comment]
I just took it for a spin, and it most assuredly does work with goiardi (and looks pretty nice, too). I have to document some other stuff anyway, so I'll stick that in there as well. Thanks!

**Comment by ctdk** [comment]
I've added a mention and link to chef-browser in the documentation in the branch that's going to be the next goiardi release pretty soon here. Thanks again for the heads up.
