### ISSUE TITLE
Provide updated Docker builds

### ISSUE THREAD

**Issue by joerg** [ctdk/goiardi#61]
Hi,

I found some images on the Docker hub (https://hub.docker.com/r/ctdk/goiardi/tags) but they are quite outdated. Please provide (automated) up-to-date builds of goiardi.

regards,
    Jörg

**Comment by ctdk** [comment]
Of course! I've been meaning to do that (and finish with some other docker work for goiardi), but keep putting it off. I'll turn that around shortly. Thanks for reminding me about it.

**Comment by ctdk** [comment]
The wheels turn slowly, but they do turn. The docker images are updated, and I'll get them added to the usual release artifact pipeline. Thanks again.
