### ISSUE TITLE
Client create fails with invalid key create_key

### ISSUE THREAD

**Issue by joerg** [ctdk/goiardi#62]
Hi,

We recently migrated from the official chef-server to goiardi and just stumbled upon an error when manually running "knife client create".

```
% knife client create delete_me -d -f delete_me.pem
ERROR: The data in your request was invalid
Response: Invalid key create_key in request body
% knife --version
Chef: 14.1.12
```
According to the chef-server API docs this create_key is valid [1], but goiardi does not know about it [2]. Currently this means for us that Terrform can not use the chef provisioner which is kind of a blocker for us. Any suggestion on how to quickly fix this? Or do you think this option could simply be added/allowed?

[1] https://docs.chef.io/api_chef_server.html#id24
[2] https://github.com/ctdk/goiardi/blob/f53c85261c0b82125ecb497370193eb68c2661a6/client/client.go#L371

**Comment by joerg** [comment]
We just compiled and run goiardi with this minimal fix of adding "create_key" to the validElements and everything seems to be in order now. If you prefer a pull request or anything just say so and we can send it to you within a day.

**Comment by ctdk** [comment]
Omg, I only just saw this. (I seem to miss many github notifications in all the noise in my primary email account.) I think this is a newer allowed element is all, and to make it pass the old Chef 11 pedant tests I had to be pretty limiting in what I'd accept.

I'll add that and see if it breaks pedant horribly. If it does, I'll do something to make it work. Thanks for finding that.

**Comment by ctdk** [comment]
I pushed it up yesterday, but that fix you made both works and doesn't appear to cause anything else to blow up. It's in both `master` and `1.0.0-dev` now, and I'll follow it up with a teensy bugfix release as well. Thanks again for bringing it to my attention, good sir.
