### ISSUE TITLE
goiardi.gl does not resolve anymore

### ISSUE THREAD

**Issue by rmoriz** [ctdk/goiardi#65]
```
Domain Name: goiardi.gl
Registry Domain ID: 30141-GL
Registry WHOIS Server:: whois.nic.gl
Updated Date: 2019-12-04T18:26:25.631Z
Creation Date: 2014-12-04T18:05:04.980Z
Registry Expiry Date: 2019-12-04T18:05:05.24Z
Registrar Registration Expiration Date: 2019-12-04T18:05:05.24Z
```

looks like the domain expired a couple of days ago but can be recovered.

**Comment by rmoriz** [comment]
I would happily sponsor the registration/renewing fees to support the project. Please drop me a line via mail roland @ moriz.de

thanks

**Comment by ctdk** [comment]
Didn't see this, but happily goiardi.gl got straightened out not long after this.
