### ISSUE TITLE
Contributing on the project

### ISSUE THREAD

**Issue by alekc** [ctdk/goiardi#67]
Hi, we'd like to contribute to the project but atm it's not clear what branch should be used. Master branch and latest stable release are pretty old atm, should we start on 1.0.0-dev?

Thanks @ctdk

**Comment by ctdk** [comment]
Hello there. Apologies for just noticing this.

To answer your question about contributing, it'll probably be more useful to work from the `1.0.0-dev` branch (which is unfortunately a bit busted at the moment, but I expect to be merging the `1.0.0-dev-shovey-auth` branch back into `1.0.0-dev` quite soon). However, if it's either specific to the current master (aka `0.11.x`) or something that's easily brought forward then working of master would also work.

Is there anything in particular you're looking to add or work on?

**Comment by alekc** [comment]
caught up on slack. Closing this
