### ISSUE TITLE
An easy installer

### ISSUE THREAD

**Issue by ctdk** [ctdk/goiardi#7]
The installation process is relatively straightforward, but an even smoother one might be nice, along with init scripts.

**Comment by rmoriz** [comment]
see also: https://github.com/whiteley/chef-goiardi

**Comment by nkts** [comment]
Why not platform/os native packages?

**Comment by rmoriz** [comment]
Looks like @ctdk is working on that using packagecloud.io https://github.com/whiteley/chef-goiardi/pull/12

**Comment by ctdk** [comment]
Yup. The packages need a little bit of work still, I think, because I think they're blowing away previous configuration files silently, and of course they need to be available for more than just certain versions of Debian and Ubuntu. Soon, though.

**Comment by ctdk** [comment]
packages have been available for a while now in packagecloud.
