### ISSUE TITLE
Knife upload user doesn't work properly

### ISSUE THREAD

**Issue by alekc** [ctdk/goiardi#75]
**Describe the bug**
When doing knife upload user, goiardi wont permit the operation because knife adds several fields which are not recognised by goiardi. 

I.e. given this user.json file
```json
{
"name": "user",
"email": "user@example.com",
"public_key": "-----BEGIN PUBLIC KEY-----xxx-----END PUBLIC KEY-----\n\n"
}
```
knife upload user will attempt following upload
```
{
   "name":"user",
   "username":"user",
   "display_name":"user",
   "admin":false,
   "json_class":"Chef::WebUIUser",
   "chef_type":"webui_user",
   "salt":null,
   "password":null,
   "openid":null,
   "email":"user@example.com",
   "public_key":"-----BEGIN PUBLIC KEY-----xxxxxx-----END PUBLIC KEY-----\n\n"
}
```
which will trigger at least 2 different failures:

1. password cannot be null (validation fails, it would not fail with "")
2. following fields are not recognised: "chef_type", "display_name", "json_class", "openid" (goiardi has a very strict validation rules, if there are any extra fields in request, it would be refused. 

**Expected behavior**
standard operation such as knife upload working

**Additional context**
This was observed on both cinc (15) and chefdk (3.9) knife versions

**Comment by ctdk** [comment]
Thanks for the PR for this. This issue is a little interesting, because the Chef 11 behavior the goiardi master branch still emulates is beginning to break more and more often. The chef pedant tests would flip out if you tried uploading extra fields, I remember, so this may be a bit delicate.

There's also a possibility that the `1.0.0-dev` and related branches may already work better. Obviously things are a bit fluid there though.

**Comment by alekc** [comment]
I can imagine. However in this case if we are forced to choose between
pedant tests and real world usage (using official tool like knife for
example) I am not sure it’s worth choosing theory over the real world.

We found this issue when migrating old chef server to gloat do through
knife backup tool. In order to make it work, several fields had to be
dropped (and we dealt with it with sed help) but what we didn’t expect is
that it would add extra fields preventing actual functionality.

**Comment by alekc** [comment]
Closed via https://github.com/ctdk/goiardi/pull/76
