### ISSUE TITLE
Clusterability

### ISSUE THREAD

**Issue by ctdk** [ctdk/goiardi#8]
This would go hand in hand with the etcd/serf/consul issue, I think. The biggest problem with clustering goiardi now is with search, since search is currently inside goiardi.

Possibilities include supporting using solr, splitting the goiardi search into its own separate program, or having the goiardi processes communicate amongst each other about updates that need indexing.

**Comment by ctdk** [comment]
This might actually work now if you run goiardi with the pg-search. Worth testing.

**Comment by d-averkiev** [comment]
Here just  to report that I have successfully running goiardy server in "cluster mode" in AWS ECS. It is working well as multiple docker containers behind ALB.
Setting used for better clusterability is:
```
GOIARDI_CONVERT_SEARCH = true
GOIARDI_PG_SEARCH = true
GOIARDI_USE_POSTGRESQL= true
GOIARDI_USE_S3_UPLOAD = true
```

**Comment by ctdk** [comment]
Works for me. Thanks for the report.
